[
build
]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "."

[
functions
]
  node_bundler = "esbuild"
  external_node_modules = ["discord.js", "ws"]

[
dev
]
  functionsPort = 8888

[[
plugins
]]
  package = "@netlify/plugin-functions-install-core"