[build]
command = "npm install && npm run build"
publish = "."
functions = "netlify/functions"

[[redirects]]
from = "/functions/*"
to = "/functions/:splat"
status = 200
force = true

[functions]
node_bundler = "esbuild"

[dev]
  autoLaunch = false