[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["discord.js"]

[functions."*"]
  timeout = 30

[[plugins]]
  package = "@netlify/plugin-functions-install-core"